---

- apt:
    state: present
    name: "{{item}}"
  with_items:
    - curl
    - gcc
    - make
    - libbz2-dev
    - libmysqlclient-dev
    - libreadline-dev
    - libssl-dev

- shell: "/home/isucon/xbuild/python-install -f 3.6.2 /home/isucon/local/python"
  args:
    creates: /home/isucon/local/python/bin/python
  become_user: isucon

- shell: PATH="/home/isucon/local/python/bin:$PATH" pip install -r requirements.txt
  args:
    chdir: /home/isucon/isubata/webapp/python
  become_user: isucon

- copy:
    src: /home/isucon/isubata/files/app/isubata.python.service
    dest: /etc/systemd/system/
    remote_src: yes
  notify: daemon-reload

- set_fact:
    app_service: python
